### ISSUE TITLE
Guice integration with Vert.x

### ISSUE THREAD

**Issue by davidsowerby** [KrailOrg/krail#671]
Initial design suggests construction of Injector in a Verticle is the best approach.

This will keep the scope of the Injector (and therefore any Singletons) to the Verticle - this seems preferable by encouraging isolation between services, rather than promoting data sharing.

Try to minimise the number of application specific classes needed to configure with Vertx

**Comment by davidsowerby** [comment]
Trying to run the krail-testapp with the Verticle annotated with `@VaadinServletConfiguration(ui = TestAppUI::class, productionMode = false)` generates this exception:


> Caused by: com.vaadin.server.ServiceException: uk.q3c.krail.testapp.TestAppUI doesn't have a public no-args constructor
	at com.vaadin.server.ServletPortletHelper.verifyUIClass(ServletPortletHelper.java:85)
	at com.vaadin.server.ServletPortletHelper.initDefaultUIProvider(ServletPortletHelper.java:160)
	at com.vaadin.server.VaadinService.createAndRegisterSession(VaadinService.java:851)
	at com.vaadin.server.VaadinService.doFindOrCreateVaadinSession(VaadinService.java:804)
	at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:744)
	at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:602)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1595)


removing the annotation generates this exception:

>Caused by: com.vaadin.server.ServiceException: No UIProvider has been added and there is no "UI" init parameter.
	at com.vaadin.server.ServletPortletHelper.checkUiProviders(ServletPortletHelper.java:193)
	at com.vaadin.server.VaadinService.onVaadinSessionStarted(VaadinService.java:905)
	at com.vaadin.server.VaadinService.createAndRegisterSession(VaadinService.java:852)
	at com.vaadin.server.VaadinService.doFindOrCreateVaadinSession(VaadinService.java:804)
	at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:744)
	at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:602)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1595)

The exact same issue has been raised [here](https://github.com/vaadin/framework/issues/8161), but that issue has been marked as stale.

Perhaps a dummy, UI with no constructor args is needed to bypass the problem

**Comment by davidsowerby** [comment]
Using a dummy no-args constructor UI fails to load the widgetset

**Comment by davidsowerby** [comment]
Thanks, I've used the `overriding VaadinVerticle.serviceInitialized` approach, as I need to override that to create the injector.  Having both in the same place means I can also solve the problem of integrating with Guice at the same time.

I think this is probably working - I now have a `java.io.NotSerializableException` from using `net.engio.mbassy.bus.SyncMessageBus`.  There must be another class going into the session store which is not covered by the Serialization tests

**Comment by davidsowerby** [comment]
A bit obvious - I missed out the UI class from the Serialization test

**Comment by davidsowerby** [comment]
Closed at Krail 0.16.8.0
