### ISSUE TITLE
Push failure on Vertx

### ISSUE THREAD

**Issue by davidsowerby** [KrailOrg/krail#701]
This occurs when any navigation is attempted:

>Error while unlocking session 
io.vertx.core.VertxException: Push failed
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushConnection.push(SockJSPushConnection.java:80)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushConnection.push(SockJSPushConnection.java:55)
	at com.vaadin.ui.UI.push(UI.java:1669)
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1027)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushHandler.callWithUi(SockJSPushHandler.java:290)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushHandler.onMessage(SockJSPushHandler.java:217)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushHandler.lambda$null$3(SockJSPushHandler.java:195)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSRoutingContext.lambda$next$1(SockJSPushHandler.java:624)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:75)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushConnection.push(SockJSPushConnection.java:77)
	... 14 more

**Comment by davidsowerby** [comment]
Moving call to ``overridePushConfiguration`` from the constructor to ``init()`` removes this exception but we get back to the ClassCastException with having the wrong PushConnection type

**Comment by davidsowerby** [comment]
Workaround in place for 0.16.8.0 - propose a change for vertx-vaadin

**Comment by davidsowerby** [comment]
See [issue in vertx-vaadin](https://github.com/mcollovati/vertx-vaadin/issues/16)
